hw_10/app_auth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path('signup/', views.RegistrationView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True), name='signin'),
    path('logout/', LogoutView.as_view(template_name='app_auth/logout.html'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='app_auth/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='app_auth/password_reset_confirm.html',
                                          success_url='/app_auth/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='app_auth/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_10/hw_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("app_auth/", include("app_auth.urls")),
]

hw_10/app_auth/models.py
from django.db import models

# Create your models here.

hw_10/app_auth/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput

class RegistrationForm(UserCreationForm):
    username = CharField(max_length=30, min_length=3, required=True, widget=TextInput(attrs={'placeholder': 'Username', "class": "form-control"}))
    email = EmailField(required=True, widget=EmailInput(attrs={'placeholder': 'Email', "class": "form-control"}))
    password1 = PasswordInput(attrs={'placeholder': 'Password', "class": "form-control"})
    password2 = PasswordInput(attrs={'placeholder': 'Confirm Password', "class": "form-control"})

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    username = CharField(max_length=30, min_length=3, required=True, widget=TextInput(attrs={'placeholder': 'Username', "class": "form-control"}))
    password = PasswordInput(attrs={'placeholder': 'Password', "class": "form-control"})

    class Meta:
        model = User
        fields = ['username', 'password']

hw_10/app_auth/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.views import View
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy



class RegistrationView(View):
    template_name = 'app_auth/registration.html'
    form_class = RegistrationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('quotes:index')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='app_auth:signin')
        return render(request, self.template_name, {'form': form})

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

hw_10/app_auth/templates/app_auth/login.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Login User</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <div class="small text-center">
            <a href="{% url 'app_auth:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_10/app_auth/templates/app_auth/logout.html
{% extends 'quotes/base.html' %}

{% block body %}

    <div class="container mt-3">
        <h1>Повертайтесь будь ласка!</h1>
    </div>

{% endblock %}

hw_10/app_auth/templates/app_auth/password_reset.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw_10/app_auth/templates/app_auth/password_reset_complete.html
{% extends 'quotes/base.html' %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw_10/app_auth/templates/app_auth/password_reset_confirm.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw_10/app_auth/templates/app_auth/password_reset_done.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw_10/app_auth/templates/app_auth/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'app_auth:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'app_auth:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw_10/app_auth/templates/app_auth/registration.html
{% extends 'quotes/base.html' %}

{% block body %}

<div class="container mt-3">
    <h2>Register User</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}