hw_10/app_auth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path('signup/', views.RegistrationView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True), name='signin'),
    path('logout/', LogoutView.as_view(template_name='app_auth/logout.html'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='app_auth/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='app_auth/password_reset_confirm.html',
                                          success_url='/app_auth/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='app_auth/password_reset_complete.html'),
         name='password_reset_complete'),
]

hw_10/hw_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("app_auth/", include("app_auth.urls")),
]

hw_10/quotes/urls.py
from django.urls import path, include

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.HomeViews.as_view(), name='index'),
    path('authors/<str:fullname>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path("tag/<str:tag>/", views.TagDetailView.as_view(), name = 'find_tag'),
    path('add-quote/', views.AddQuoteView.as_view(), name='add-quote'),
    path('add-author/', views.AddAuthorView.as_view(), name='add-author')
]

hw_10/quotes/models.py
from mongoengine import connect, Document, StringField, ListField, ReferenceField, CASCADE

class Author(Document):
    fullname = StringField(required=True, unique=True)
    born_date = StringField(max_length=50)
    born_location = StringField(max_length=150)
    description = StringField()
    meta = {'collection': 'authors'}

class Quote(Document):
    tags = ListField(StringField(max_length=50))
    author = ReferenceField(Author, reverse_delete_rule=CASCADE)
    quote = StringField()
    meta = {'collection': 'qoutes'}

hw_10/quotes/forms.py
from django.forms import CharField, TextInput, ChoiceField, Textarea, Select
from django import forms
from .models import Author, Quote


class QuoteForm(forms.Form):
    quote = CharField(label="Quote", widget=Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your quote'}), required=True)
    author = forms.ChoiceField(
        label="Author",
        widget=Select(attrs={"class": "form-control"}),
        required=True
    )
    tags = CharField(label="Tags (comma-separated)", widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'tag1, tag2,tag3 ...'}), required=True)

    def __init__(self, *args, **kwargs):
        super(QuoteForm, self).__init__(*args, **kwargs)
        self.fields['author'].choices = [(str(author.id), author.fullname) for author in Author.objects]

    def clean_tags(self):
        tags_str = self.cleaned_data['tags']
        return [tag.strip() for tag in tags_str.split(',') if tag.strip()]

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']


class AuthorForm(forms.Form):
    fullname = CharField(label="Fullname", widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Fullname'}), required=True)
    born_date = CharField(label="Born_date", widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Born date'}), required=True)
    born_location = CharField(label="Born_location", widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Born location'}), required=True)
    description = CharField(label="Description", widget=Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}), required=True)

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

hw_10/quotes/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Quote, Author
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import QuoteForm, AuthorForm


class HomeViews(View):
    template_name = 'quotes/index.html'

    def get(self, request):
        quotes = Quote.objects.all()
        return render(request, self.template_name, {'quotes': quotes})


class AuthorDetailView(View):
    template_name = 'quotes/author_detail.html'

    def get(self, request, fullname):
        author = Author.objects.get(fullname=fullname)
        return render(request, self.template_name, {'author': author})


class TagDetailView(LoginRequiredMixin, View):
    login_url = '/app_auth/signin/'
    template_name = 'quotes/find_tag.html'

    def get(self, request, tag):
        quotes = Quote.objects.filter(tags=tag)
        return render(request, self.template_name, {'quotes': quotes, 'tag': tag})


class AddQuoteView(LoginRequiredMixin, View):
    login_url = '/app_auth/signin/'
    template_name = 'quotes/add-quote.html'
    form_class = QuoteForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            quote_text = form.cleaned_data['quote']
            author = form.cleaned_data['author']
            tags = form.cleaned_data['tags']

            new_quote = Quote(quote=quote_text, author=author, tags=tags)
            new_quote.save()
            return redirect('quotes:index')
        return render(request, self.template_name, {'form': form})


class AddAuthorView(LoginRequiredMixin, View):
    login_url = '/app_auth/signin/'
    template_name = 'quotes/add-author.html'
    form_class = AuthorForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            fullname = form.cleaned_data['fullname']
            born_date = form.cleaned_data['born_date']
            born_location = form.cleaned_data['born_location']
            description = form.cleaned_data['description']

            new_author = Author(fullname=fullname, born_date=born_date, born_location=born_location, description=description)
            new_author.save()
            return redirect('quotes:index')
        return render(request, self.template_name, {'form': form})

hw_10/quotes/templates/quotes/add-author.html
{%  extends 'quotes/base.html' %}

{% block body %}
    <div class="container mt-4">
    <h2>Add a New Author</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Author</button>
    </form>
</div>
{% endblock %}

hw_10/quotes/templates/quotes/add-quote.html
{%  extends 'quotes/base.html' %}

{% block body %}
    <div class="container mt-4">
    <h2>Add a New Quote</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Quote</button>
    </form>
</div>
{% endblock %}

hw_10/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>
{% endblock %}

hw_10/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css'%}">
    <title>Home work 10</title>
</head>
<body>
<div class="row header-box">
    <div class="col-md-8">
        <h1>
            <a href="/" style="text-decoration: none">Quotes to Scrape</a>
        </h1>
    </div>
    <div class="col-md-4">
        <p>
            {% if user.is_authenticated %}
        <form action="{% url 'app_auth:logout' %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-link" style="margin-left:50px;">
                Logout
            </button>
        </form>
        <a href="{% url 'quotes:add-quote' %}">Add new quote</a>
        <a href="{% url 'quotes:add-author' %}" style="margin-left:25px;">Add new author</a>

        {% else %}
        <a href="{% url 'app_auth:signup' %}">Register</a>
        <a href="{% url 'app_auth:signin' %}">Login</a>
        {% endif %}

        </p>
    </div>
</div>
{% block body %}
{% endblock %}
</body>
</html>

hw_10/quotes/templates/quotes/find_tag.html
{% extends 'quotes/base.html' %}

{% block body %}

<h3>Viewing tag: <a href="{% url 'quotes:find_tag' tag %}">{{ tag }}</a></h3>
<div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
        <a href="{% url 'quotes:author_detail' quote.author.fullname %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world">
            {% for tag in quote.tags %}

            <a class="tag" href="{% url 'quotes:find_tag' tag %}">{{ tag }}</a>

            {% endfor %}
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

hw_10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block body %}

<div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
        <a href="{% url 'quotes:author_detail' quote.author.fullname %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world">
            {% for tag in quote.tags %}

            <a class="tag" href="{% url 'quotes:find_tag' tag %}">{{ tag }}</a>

            {% endfor %}
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}